"""empty message

Revision ID: a46f36619f8e
Revises: 7f52ffb849bf
Create Date: 2023-06-09 21:34:05.118601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a46f36619f8e'
down_revision = '7f52ffb849bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('enroll', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('personal_info', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('caltoolstable')
    op.drop_table('ticketstable')
    op.drop_table('toolhistorytable')
    op.drop_table('userstable')
    op.drop_table('materiallisttable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiallisttable',
    sa.Column('MaterialName', mysql.TEXT(), nullable=True),
    sa.Column('Category', mysql.TEXT(), nullable=True),
    sa.Column('AdditionalNotes', mysql.TEXT(), nullable=True),
    sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NVL', mysql.TEXT(), nullable=True),
    sa.Column('BEN', mysql.TEXT(), nullable=True),
    sa.Column('CurrentState', mysql.TEXT(), nullable=True),
    sa.Column('LamPartNumber', mysql.TEXT(), nullable=True),
    sa.Column('RecordIDNumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SerialNumber', mysql.TEXT(), nullable=True),
    sa.Column('materialPK', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Location', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('materialPK'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userstable',
    sa.Column('username', mysql.TEXT(), nullable=True),
    sa.Column('pword', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('toolhistorytable',
    sa.Column('NVL', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employeeID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('newLoc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('curDate', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ticketstable',
    sa.Column('TicketStatus', mysql.TEXT(), nullable=True),
    sa.Column('TicketNum', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('BEN', mysql.TEXT(), nullable=True),
    sa.Column('TicketDescription', mysql.TEXT(), nullable=True),
    sa.Column('Department', mysql.TEXT(), nullable=True),
    sa.Column('ToolBay', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('TicketNum'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('caltoolstable',
    sa.Column('ID', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ManufacturerName', mysql.TEXT(), nullable=True),
    sa.Column('ModelName', mysql.TEXT(), nullable=True),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('SerialNumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Area', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Location', mysql.TEXT(), nullable=True),
    sa.Column('CalibrationDue', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID', 'Area'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('student')
    # ### end Alembic commands ###
